import type { Metadata } from 'next';
import Link from 'next/link';
import './globals.css';
import { Toaster } from 'react-hot-toast';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-gray-50 text-gray-900">
        <header className="p-4 bg-white shadow-md">
          <nav className="flex space-x-4">
            <Link href="/">Home</Link>
            <Link href="/add">Add Beer</Link>
          </nav>
        </header>
        <main className="p-8">
          {children}
          <Toaster position="bottom-right" reverseOrder={false} />
        </main>
      </body>
    </html>
  );
}
