import type { Metadata } from "next";
import Link from 'next/link';
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from 'react-hot-toast';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-gray-50 text-gray-900">
        <header className="p-4 bg-white shadow-md">
          <nav className="flex space-x-4">
            <Link href="/">Home</Link>
            <Link href="/add">Add Beer</Link>
          </nav>
        </header>
        <main className="p-8">
          {children}
          <Toaster
            position="bottom-right"
            reverseOrder={false}
          />
        </main>
      </body>
    </html>
  );
}
